const Discord = require("discord.js")
const Config = require("../config.json")

module.exports.run = async (bot, message, args) => {
    var message_copy = message
    try {
        await messag.delete()
    } catch (error) { console.error(error) }
    var dm = await message_copy.author.createDM()
    const embed = new Discord.RichEmbed()
        .setTitle(`🛡️${bot.user.username}🛡️ commands at your service:`)
        .setColor(0xFF0000)
        .setDescription("**!schedule <date>** - generates an interactable raid schedule. For <date> use mon or monday for the next Monday, wed or wednesday for the next Wednesday or YYYY.MM.DD for a different date. \n**!refresh** - revitalizes old schedules after bot has been restarted. \n**!archive** - moves all messages generated by this bot to the \#archive channel. \n**!clean** - cleans all messages starting with \"!\". \n**!help** - sends this message to you by dm.")
    try {
        console.log(embed)
        dm.send(embed)
    } catch (error) { console.error(error) }
}

module.exports.help = {
    name: "help"
}