const Discord = require("discord.js")

module.exports.run = async (bot, message, args) => {
    var message_copy = message
    try {
        await message.delete()
    } catch (error) { console.error(error) }
    var dm = await message_copy.author.createDM()
    const embed = new Discord.MessageEmbed()
        .setTitle(`🛡️${bot.user.username}🛡️ commands at your service:`)
        .setColor(0xFF0000)
        .setDescription("**!schedule <date> <desc>** - generates an interactable raid schedule. For <date> use mon or monday for the next Monday, tue or tuesday for the next Tuesday and so on. You can also use YYYY.MM.DD for a date that isn't next week. For <desc> add an optional description for the schedule. \n**!mon <desc>** - shortened version of !schedule monday <desc>. Also works for other days of the week. \n**!setdesc <description>** - sets the default description for your schedule. \n**!addrole <name of role>** - creates a new role to be presented in the schedule. \n**!removerole <name of role>** - removes a roles from the list of roles. \n**!roles** - shows the current roles and their respective emojis. \n**!refresh** - revitalizes old messages after bot has been restarted. \n**!archive** - moves all messages generated by this bot to the \#archive channel. \n**!clean** - cleans all messages starting with \"!\". \n**!help** - sends this message to you.")
    try {
        dm.send(embed)
    } catch (error) { console.error(error) }
}

module.exports.help = {
    name: "help"
}